title: Singapore Customs
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/favicon.png

# Site colors
colors:
  primary-color: '#041D42'
  secondary-color: '#041D42'
  media-colors:
    - title: media-color-one
      color: '#A2AAAD'
    - title: media-color-two
      color: '#20639B'
    - title: media-color-three
      color: '#990000'
    - title: media-color-four
      color: '#F5C936'
    - title: media-color-five
      color: '#041D42'

resources_name: news-and-media

collections:
  about-us:
    output: true
  individuals:
    output: true
  businesses:
    output: true
  news-and-media:
    output: true
  eservices:
    output: true
  going-through-customs:
    output: true
  registration-matters:
    output: true
  business-resources:
    output: true
  importing-goods: 
    output: true
  transhipping-goods: 
    output: true
  transhipment-procedures:
    output: true
  chemical-weapons-convention: 
    output: true
  inspections: 
    output: true
  licensing-requirements: 
    output: true
  strategic-goods-control: 
    output: true
  strategic-goods-control-1: 
    output: true
  customs-schemes-licences-framework: 
    output: true
  valuation-duties-taxes-fees: 
    output: true
  import-procedures: 
    output: true
  importing-by-post-or-courier-service:
    output: true
  temporary-import-scheme:
    output: true
  temporary-import-scheme-2: 
    output: true
  importing-dutiable-motor-vehicles:
    output: true
  guide-to-importing-dutiable-motor-vehicles:
    output: true
  importing-goods-for-destruction-or-recycling:
    output: true
  export-procedures:
    output: true
  authorised-piers-places: 
    output: true
  united-nations-security-council-sanctions: 
    output: true
  strategic-goods-control-list:
    output: true
  strategic-goods-control-list-2:
    output: true
  import-certificate-and-delivery-verification:
    output: true
  test_hidden:
    output: true
  business_hidden_tradenet:
    output: true 
  exporting-goods:
    output: true   
  security-lodgement:
    output: true    
  business_hidden_apply-update-renew-terminate-declarant-agent:
    output: true   
  organisation-overview:
    output: true 
  importing-investment-precious-metals:   
    output: true   
  business_hidden_competent-authorities-requirements:   
    output: true  
  competent-authorities-requirements:   
    output: true          
##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test

